<a href="https://colab.research.google.com/github/BhaveshWadibhasme/Pytorch/blob/master/Multi_dimentional_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import torch
import warnings
warnings.filterwarnings('ignore')

In [0]:
#---------------Define_tensor-----------------------
ten_one = torch.tensor([1,2,3,4,])
print("This is one dimentional_tensor:{}".format(ten_one))

This is one dimentional_tensor:tensor([1, 2, 3, 4])


In [0]:
#-------------Create_two_dimentional_tensor-------------------
ten_two = torch.range(0,9)
ten_two = ten_two.view(5,2)
print("The is two dimentional_tensor:\n{}".format(ten_two))

The is two dimentional_tensor:
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [0]:
#-----------Create_multidimentional_tensor------------------------
ten_three = torch.range(1,27)
ten_three = ten_three.view(3,3,3)
print("This is three dimentional_tensorL:\n{}".format(ten_three))

This is three dimentional_tensorL:
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])


In [0]:
#-------------Findout_dimention_of_tensor----------------
print("The dimention of tensor ten_one is :{}".format(ten_one.dim()))
print("The dimention of tensor ten_two is :{}".format(ten_two.dim()))
print("The dimention of tensor ten_three is:{}".format(ten_three.dim()))


The dimention of tensor ten_one is :1
The dimention of tensor ten_two is :2
The dimention of tensor ten_three is:3


In [31]:
ten_three

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])

In [35]:
#---------Slice_first_layer-------------
ten_four = ten_three[0,:,:]
print(ten_four)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [34]:
#----------Slice_second_layer------------
ten_five = ten_three[1,:,:]
print(ten_four)

tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])


In [33]:
#------------------Slice_third_layer------------
ten_six = ten_three[2,:,:]
print(ten_six)

tensor([[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]])


In [42]:
ten_three

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])

In [41]:
#---------------Slice_first_column_of_first_slice_from_above_tensor---------------
["slice_index", 'index_of_elements_to_extract','column_name']
ten_seven = ten_three[0,0:3,0]
print(ten_seven)

tensor([1., 4., 7.])
