<a href="https://colab.research.google.com/github/BhaveshWadibhasme/Pytorch/blob/master/Multi_dimentional_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import torch
import warnings
warnings.filterwarnings('ignore')

In [3]:
#---------------Define_tensor-----------------------
ten_one = torch.tensor([1,2,3,4,])
print("This is one dimentional_tensor:{}".format(ten_one))

This is one dimentional_tensor:tensor([1, 2, 3, 4])


In [4]:
#-------------Create_two_dimentional_tensor-------------------
ten_two = torch.range(0,9)
ten_two = ten_two.view(5,2)
print("The is two dimentional_tensor:\n{}".format(ten_two))

The is two dimentional_tensor:
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [5]:
#-----------Create_multidimentional_tensor------------------------
ten_three = torch.range(1,27)
ten_three = ten_three.view(3,3,3)
print("This is three dimentional_tensorL:\n{}".format(ten_three))

This is three dimentional_tensorL:
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])


In [6]:
#-------------Findout_dimention_of_tensor----------------
print("The dimention of tensor ten_one is :{}".format(ten_one.dim()))
print("The dimention of tensor ten_two is :{}".format(ten_two.dim()))
print("The dimention of tensor ten_three is:{}".format(ten_three.dim()))


The dimention of tensor ten_one is :1
The dimention of tensor ten_two is :2
The dimention of tensor ten_three is:3


In [27]:
#----------------Create_2D_tensor_manually------------------
two_dim_tensor = torch.tensor([[1,2],[3,4],[5,5]])
print(two_dim_tensor)
print()
print("The dimention of above tensor is:{}".format(two_dim_tensor.dim()))

tensor([[1, 2],
        [3, 4],
        [5, 5]])

The dimention of above tensor is:2


In [7]:
ten_three

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])

In [8]:
#---------Slice_first_layer-------------
ten_four = ten_three[0,:,:]
print(ten_four)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [9]:
#----------Slice_second_layer------------
ten_five = ten_three[1,:,:]
print(ten_four)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [10]:
#------------------Slice_third_layer------------
ten_six = ten_three[2,:,:]
print(ten_six)

tensor([[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]])


In [11]:
ten_three

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])

In [12]:
#---------------Slice_first_column_of_first_slice_from_above_tensor---------------
["slice_index", 'index_of_elements_to_extract','column_name']
ten_seven = ten_three[0,0:3,0]
print(ten_seven)

tensor([1., 4., 7.])


## **Matrix** **Multiplication:**

The necessary conditon for multiplication of matrix is the number of columns of first matrix need to be equal to number of column of second matrix.
 








In [21]:
#----------Declare_two_matric_and_perform_their_multiplication--------------
matrix_A  = torch.range(1,6).view(3,2)
matrix_B  = torch.range(1,6).view(2,3)
print("The matrix A is:\n{}".format(matrix_A),"\nThe matrix B is:\n{}".format(matrix_B))
print()
print("The multiplication of matrix_A and matrix_B is: \n{}".format(torch.matmul(matrix_A,matrix_B)))

The matrix A is:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 
The matrix B is:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

The multiplication of matrix_A and matrix_B is: 
tensor([[ 9., 12., 15.],
        [19., 26., 33.],
        [29., 40., 51.]])


In [28]:
#----------------Alternative_to_matmul_function----------------------------
new_matrix = matrix_A @ matrix_B
print("The result of matrix multiplication is:\n{}".format(new_matrix))

The result of matrix multiplication is:
tensor([[ 9., 12., 15.],
        [19., 26., 33.],
        [29., 40., 51.]])
